### ISSUE TITLE
Support for React v18

### ISSUE THREAD

**Issue by smitroshin** [reactivando/use-pubsub-js#25]
Are there any plans to support React 18 ?

**Comment by AZagatti** [comment]
Hi @smitroshin, can you tell me what exact problem with React 18 you had? I can debug better

**Comment by smitroshin** [comment]
> Hi @smitroshin, can you tell me what exact problem with React 18 you had? I can debug better

Package has now strictly react 17 as peer dependency.
My package manager is able to have an error at installation if I migrate to react 18.

**Comment by AZagatti** [comment]
I change peerDependencies, can you try new version?
https://www.npmjs.com/package/use-pubsub-js/v/1.0.7
